version: "3.7"
services:
  database:
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./database/mysql:/var/lib/mysql"
  nginx:
    image: nginx:1.17
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./web/dist/:/usr/share/nginx/public/"
    links:
      - web
      - server
  server:
    build:
      context: ./leaf
      dockerfile: ./Dockerfile
    restart: always
    links:
      - database
    depends_on:
      - database
  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - "./web:/web"
#  centos:
#    build:
#      context: ./centos
#      dockerfile: ./Dockerfile
#    extra_hosts:
#      - "mac:192.168.1.10"
