version: "3.7"
services:
  nginx:
    image: nginx:1.17
    ports:
      - "80:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./web/dist/:/usr/share/nginx/public/"
    extra_hosts:
      - "mac:10.2.21.249"
#      - "mac:192.168.1.10"
#  leaf:
#    build:
#      context: ./leaf
#      dockerfile: ./Dockerfile
#  centos:
#    build:
#      context: ./centos
#      dockerfile: ./Dockerfile
#    extra_hosts:
#      - "mac:192.168.1.10"
